// Auto-Generated by FAKE; do not edit
namespace System

open System.Runtime.Versioning

[<assembly: SupportedOSPlatform("Plainion.Windows.Specs")>]
do ()

module internal AssemblyVersionInformation2 =
    let [<Literal>] SupportedOSPlatform = "Plainion.Windows.Specs"
