// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Plainion.Windows")]
[assembly: AssemblyProduct("Plainion.Windows")]
[assembly: AssemblyDescription("Plainion.Windows")]
[assembly: AssemblyCopyright("Copyright @ 2022")]
[assembly: AssemblyVersion("4.0.1")]
[assembly: AssemblyFileVersion("4.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.Windows";
        internal const System.String AssemblyProduct = "Plainion.Windows";
        internal const System.String AssemblyDescription = "Plainion.Windows";
        internal const System.String AssemblyCopyright = "Copyright @ 2022";
        internal const System.String AssemblyVersion = "4.0.1";
        internal const System.String AssemblyFileVersion = "4.0.1";
    }
}
