// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.Windows")]
[assembly: AssemblyProductAttribute("Plainion.Windows")]
[assembly: AssemblyDescriptionAttribute("Plainion.Windows")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2018")]
[assembly: AssemblyVersionAttribute("2.11.0")]
[assembly: AssemblyFileVersionAttribute("2.11.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.Windows";
        internal const System.String AssemblyProduct = "Plainion.Windows";
        internal const System.String AssemblyDescription = "Plainion.Windows";
        internal const System.String AssemblyCopyright = "Copyright @ 2018";
        internal const System.String AssemblyVersion = "2.11.0";
        internal const System.String AssemblyFileVersion = "2.11.0";
    }
}
