// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.Windows.Tests")]
[assembly: AssemblyProductAttribute("Plainion.Windows")]
[assembly: AssemblyDescriptionAttribute("Plainion.Windows")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2017")]
[assembly: AssemblyVersionAttribute("2.3.0")]
[assembly: AssemblyFileVersionAttribute("2.3.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.Windows.Tests";
        internal const System.String AssemblyProduct = "Plainion.Windows";
        internal const System.String AssemblyDescription = "Plainion.Windows";
        internal const System.String AssemblyCopyright = "Copyright @ 2017";
        internal const System.String AssemblyVersion = "2.3.0";
        internal const System.String AssemblyFileVersion = "2.3.0";
    }
}
